name: setup-ock
description: Installs ock and adds it to the PATH
inputs:
  version:
    default: latest
runs:
  # TODO(slewiskelly): Download a pre-built version directly from a published
  # release.
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Install
      run: |
        go install github.com/slewiskelly/ock/cmd/ock@${{ inputs.version }}
      shell: bash
