name: Image
on:
  release:
    types:
    - published
env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}
jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
      - name: Build & push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          push-to-registry: true
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}
